Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "arhitekt-vm"

    #port forwarding
    #config.vm.network "forwarded_port", guest: 5059, host: 5059
    config.vm.network "private_network", ip: "192.168.56.10"


    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
    end

    # #shell provision
    # config.vm.provision "shell", path: "provision.sh"
    
    #ansible 
    config.vm.provision("ansible") do |ansible|
        ansible.playbook = "playbook.yaml"
    end
     
end 