Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "arhitekt-vm"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
    end

    config.vm.provision "shell", path: "provision.sh"
    

    # # Ansible provisioner
    # config.vm.provision("ansible") do |ansible|
    #     ansible.playbook = "playbook.yaml"
    # end
     
end